### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by TyrionFront** [asciinema/asciicast2gif#50] opened 2018-10-16 11:34 UTC
On Ubuntu 18.04 LTS with all previously installed additional packages I still can't get the result I expect.  
Here is the output I have every time (in attachment)
![screenshot from 2018-10-16 14-23-48](https://user-images.githubusercontent.com/18406903/47013651-a031b080-d150-11e8-925b-d5991d3186d4.png)

**Comment by sickill** [comment] 2018-11-16 19:23
@TyrionFront does this happen on this particular recording or on all you tried?

**Comment by TyrionFront** [comment] 2018-11-17 07:59
This response occurs on two videos i try to modify. I can't describe you all the additional details because I did my attempt, as U can see, about a month ago.

**Comment by sickill** [comment] 2018-11-18 10:57
Ok. Since this most likely is a duplicate of #20 I'll close this one, and feel free to follow there.

**Closed by sickill** 2018-11-18 10:57 UTC
